### ISSUE TITLE
.CMsgClientLogon#persona_name is not a field: undefined

### ISSUE THREAD

**Issue by FrostBy** [Arcana/node-dota2-bot#8]
Hi! If i want to post persona_name with logonDetails to the constuctor, it throws this error
"persona_name" field not exist in CMsgClientLogon

**Comment by Crazy-Duck** [comment]
I confirm this is a bug, I'll try to fix asap.

**Comment by csplkiller** [comment]
I have a large number of bots running at the same time, and I often get an error:

/scripts/dota2/bot/node_modules/steam/node_modules/steam-resources/node_modules/protobufjs/dist/ProtoBuf.js:2440
                            throw Error(this+"#"+keyOrObj+" is not a field: undefined");
                            ^

Error: .CMsgClientLogon#persona_name is not a field: undefined
    at MessagePrototype.set (/scripts/dota2/bot/node_modules/steam/node_modules/steam-resources/node_modules/protobufjs/dist/ProtoBuf.js:2440:35)
    at MessagePrototype.set (/scripts/dota2/bot/node_modules/steam/node_modules/steam-resources/node_modules/protobufjs/dist/ProtoBuf.js:2434:38)
    at Message (/scripts/dota2/bot/node_modules/steam/node_modules/steam-resources/node_modules/protobufjs/dist/ProtoBuf.js:2363:34)
    at SteamUser.logOn (/scripts/dota2/bot/node_modules/steam/lib/handlers/user/index.js:33:6)
    at SteamClient.onSteamLogOff (/scripts/dota2/bot/node_modules/dota2-bot/index.js:77:28)
    at emitOne (events.js:115:13)
    at SteamClient.emit (events.js:210:7)
    at SteamClient.handlers.(anonymous function) (/scripts/dota2/bot/node_modules/steam/lib/steam_client.js:290:8)
    at SteamClient._netMsgReceived (/scripts/dota2/bot/node_modules/steam/lib/steam_client.js:157:26)
    at SteamClient.handlers.(anonymous function) (/scripts/dota2/bot/node_modules/steam/lib/steam_client.js:259:10)


Judging by the correction presented above, I think it is necessary to make another correction when reconnecting.

Line 77
self.steamUser.logOn(self._logonDetails);

Replace by:

self.steamUser.logOn({"account_name": self._logonDetails.account_name, "password": self._logonDetails.password});

Right ?
